/**
 * 
 */
package com.ideafactory.heroes;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.repository.CrudRepository;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.ideafactory.heroes.models.Hero;
import com.ideafactory.heroes.models.HeroesRepository;

import java.util.List;

/**
 * @author Aélion
 *
 */
@RequestMapping(path="/api/v1")
@RestController
public class HeroesController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private HeroesRepository heroesRepository;
	
	public HeroesController() {
	}
	
	@GetMapping("/all")
	public Iterable<Hero> getAll() {
		return this.heroesRepository.findAll();
	}

	
	@PostMapping("/add")
	public Hero addHero(@RequestBody Hero hero) {
		this.heroesRepository.save(hero);
		
		return hero;
	}
	
	@PutMapping("/update")
	public Iterable<Hero> updateHero(@RequestBody Hero hero) {
		this.heroesRepository.save(hero);
		return this.getAll();
	}
	@DeleteMapping("/delete/{id}")
	public ResponseEntity<?> deleteHero(@PathVariable int id) {
		this.heroesRepository.deleteById(id);

		return new ResponseEntity<>(this.getAll(), HttpStatus.OK);

	}
}
